# Generated by Django 4.0.10 on 2024-05-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pet_adopted_by_pet_is_adopted_user_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pet_images/'),
        ),
    ]
